### ISSUE TITLE
Add support for interoperability

### ISSUE THREAD

**Issue by clemherreman** [mrkrstphr/array-config#4] opened 2014-11-09 14:16 UTC
Hello,

First, thank you a lot for your work! I'd like to use some configuration in a mrkrstphr/array-config from another tool in my platform, that is written in python. It's an application that monitors my PHP daemons _(which are using mrkrstphr/array-config files)_ and triggers our 24/7 on-call support.

Do you have a roadmap for supporting such cases, as there is no valid reasons not to use PHP arrays as config?

**Comment by bweston92** [comment] 2017-01-04 08:38
I like the pun however, use a distributed configuration. Use something like Etcd and have the configuration updated in both places by something like Confd.

**Comment by mrkrstphr** [comment] 2017-10-04 15:34
Duplicate of #1, closing, wontfix, yolo.

**Closed by mrkrstphr** 2017-10-04 15:34 UTC
